### ISSUE TITLE
Question: what version of the vuforia sdk is used in the plugin ?

### ISSUE THREAD

**Issue by nleclerc** [mattrayner/cordova-plugin-vuforia#65]
We have seen that there's a problem when the scanner view rotates on ios.
It looks like everything is fine but the actual image is stretched.
It might be a sdk bug (as mentionned in [this forum post](https://developer.vuforia.com/forum/unity-extension-technical-discussion/camera-view-stretched-and-rotation-90-deg-unity-451-and-vuforia-305)) so it would be quite helpful to know what we're working with.

Thanks.

**Comment by nleclerc** [comment]
More on the subject : https://developer.vuforia.com/forum/ios/camera-ratio-retina-devices?sort=2

**Comment by mattrayner** [comment]
We're using Cordova V4 inside of the plugin as that's what was around when we made it.

The rotation thing is 'known' - we've written some code to detect device rotation and start/stop Vuforia - this is a fix in 90% of scenarios. The issue is to do with how fast a user 'spins' the device. If they quickly got from portrait - horizontal - portrait - horizontal Vuforia gets confused as to what orientation the camera should be displayed in - thus causing the 'stretch' issue. In reality we've never received a user issue based on this and consider it an edge case.

**Comment by nleclerc** [comment]
What exact version are we talking about ?

BTW, in our tests, we get the rotation pb 100% of the time on retina devices.
On a non retina device it works fine.

**Comment by mattrayner** [comment]
I'm not sure of the exact dot version I'm afraid :-1:

That's interesting - which device in particular?

**Comment by nleclerc** [comment]
We're seeing the pb using an ipod touch and an ipad mini 2.
Works fine on an ipad mini 1.

**Comment by mattrayner** [comment]
@nleclerc, have you had a chance to look into this or thought of a potential solution?

**Comment by nleclerc** [comment]
Not really i'm afraid.
We've been busy preparing a special event for this weekend so didn't get much time to spend on this subject. Our current goal is to be able to lock rotation so the problem doesn't occur but this hasn't been easy as pie. Looks like everyone is struggling with UINavigationController orientation.

I'm wondering if it wouldn't be easier to just upgrade to the newer vuforia sdk.

**Comment by nleclerc** [comment]
Ok so we managed to resolve the orientation issue (see https://github.com/mattrayner/cordova-plugin-vuforia/pull/84).

I'm still quite keen on upgrading the SDK to v5 though.
