### ISSUE TITLE
error building for IOS platform with cordova cli

### ISSUE THREAD

**Issue by elenaaralla** [mattrayner/cordova-plugin-vuforia#94]
​
Hi,
I'm having problem building a sample project with vuforia plugin, for IOS; 
this is the error:

========
... libVuforia.a, missing required architecture i386

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/Hello\ World.app/Hello\ World normal i386
========

I've installed the Phonegap sample app (HelloWorld) with this comand:

`phonegap create myApp
`
I've added platform (Android and IOS) and build

```
cordova platform add android
cordova build android
cordova platform add ios
cordova build ios
```
no build error...
I've added vuforia plugin with command:

`cordova plugin add cordova-plugin-vuforia
`
and re-build the app for android (no build error)
and ios --> BUILD ERROR

## Expected Behavior

It should build for ios with no issue

​
## Current Behavior

error building for ios

​
## Possible Solution

​
## Steps to Reproduce (for bugs)

1. installaphonegap sample app (phonegap create myApp)
2. add vuforia cordova plugin (cordova plugin add cordova-plugin-vuforia)
3. prepare and build for IOS

## Context

​
## Your Environment

* Cordova version used: 6.3.0
* Plugin version used: 3.0.2
* Plaforms affected: iOS
* iOS/Android versions affected: 

I'm using cordova cli on mac El Capitain

thank you for your help

**Comment by mattrayner** [comment]
Hi @elenaaralla - this is actually expected :-1:

Because of the use of the Vuforia library, you can't complete the build using the command line.

Basically what happens when you build from the commandline, or for any of the simulators in Xcode, the compiler tries to build the project to be run on the 'target' architecture. Your machine's architecture is `i386`, however an actual device's architecture is `arm`.

In order to get it to build you need to do one of two things, either use the command `cordova run ios --device` with a development enabled iDevice attached (this may not always fix it depending on how you're set up). Alternatively, the way I do it is to run `cordova build ios` in the command line (this will copy all of your 'Cordova' files i.e. www, js, etc. Then, run `open platforms/ios/*.xcodeproj`. This will open your Cordova Xcode project in Xcode. From here you can select your attached device and build/run. You should find it will work in this configuration, you just need to tell the compiler that you don't plan on running the code on your `i386` mac, but instead on an `arm` device.

**Comment by mattrayner** [comment]
In the README, under Requirements, we have the following:

> **NOTE:** You will require an Android or iOS device for development and testing. Cordova-Plugin-Vuforia requires hardware and software support that is not present in either the iOS or Android simulators.

**Comment by elenaaralla** [comment]
Hi,

thank you; I missed the NOTE under requirement :-)
I'll try with attached device and let you know.
Thanks again,
bye, elena.

**Comment by elenaaralla** [comment]
Hi,

I was able to build my sample app on device, using XCode.
Thank you very much, elena.

**Comment by mattrayner** [comment]
Glad you got it working :smile:
